name: Build and Release Binaries
on:
  pull_request:
    branches:
      - '*'
jobs:
  release:
    strategy:
      matrix:
        go_version: [1.17.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Set CLI_VERSION
        run: echo "CLI_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )" >> $GITHUB_ENV

      - name: Configure & Build
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: wallet-commander
          targets: windows/amd64,linux/amd64,darwin/amd64,darwin/arm64
          v: true
          x: false
          ldflags: -X "github.com/earn-alliance/wallet-commander/internal/config.Version=${{ env.CLI_VERSION }}"